### ISSUE TITLE
Clear project removes all classes. Cannot add another.

### ISSUE THREAD

**Issue by bcb13** [KN4CK3R/ReClass.NET#10]
It would be nice if you could add a class by right clicking in the left panel.

**Comment by bcb13** [comment]
I'm blind. I just noticed the add a class to this project button.

**Comment by KN4CK3R** [comment]
![grafik](https://cloud.githubusercontent.com/assets/1666336/22620258/15416c5c-eb08-11e6-8ff2-32c205e647ec.png)
Added a context menu entry.
