### ISSUE TITLE
Build on linux

### ISSUE THREAD

**Issue by lexesv** [KN4CK3R/ReClass.NET#13]
Hello

I try build sln on linux in Rider
And got error:
![_2017-08-07_18-15-15](https://user-images.githubusercontent.com/15149258/29033051-696a2c04-7b9c-11e7-8cca-182e00482f31.png)

![_2017-08-07_18-16-29](https://user-images.githubusercontent.com/15149258/29033097-948431f0-7b9c-11e7-909e-0d28a08211b9.png)

**Comment by KN4CK3R** [comment]
I don't know Rider. For my tests I just compiled ReClass.NET with Visual Studio and ran it with Mono in Ubuntu. Don't know what Rider doesn't like from the sln file.

**Comment by lexesv** [comment]
Rider
https://www.jetbrains.com/rider/

So you did not compile the project in a Linux environment?

**Comment by KN4CK3R** [comment]
No, I compiled ReClass.NET with Visual Studio on Windows and the native library was compiled with Visual Studio remotely on Ubuntu in a virtual machine.

A quick google search just brought this: https://rider-support.jetbrains.com/hc/en-us/community/posts/115000088090-C-Project-support

**Comment by KN4CK3R** [comment]
The problem with Rider should be that Rider is only a .NET IDE but the ReClass.NET project contains native C++ code too. That would explain the error messages in the event log you see.

**Comment by lexesv** [comment]
OK. My whole problem is that I can not compile plugins.
Tell me please, where can I download them? Because I have no way to install  Windows and Visual Studio.

**Comment by lexesv** [comment]
OK. My whole problem is that I can not compile LoadBinaryPlugin.
Tell me please, where can I download it? Because I have no way to install Windows and Visual Studio.

**Comment by KN4CK3R** [comment]
Is your compile problem the reference to the ReClass.NET.csproj which you can't compile? You can simply remove this reference and use the provided ReClass.NET.exe as reference.
