### ISSUE TITLE
Adjustable Tooltip Size When Previewing A Pointer

### ISSUE THREAD

**Issue by KittoniuM** [KN4CK3R/ReClass.NET#14]
i had this idea where you can adjust the size of the tooltip that pops up when you're hovering over a pointer, basically, you could scroll your mousewheel to make it bigger or smaller, just like when hovering over a sub_ in ida :D?

**Comment by KN4CK3R** [comment]
Good idea but not possible with the current implementation of the tooltip (a limitation of WinForms). I will have to implement a custom tooltip class for this.

**Comment by KN4CK3R** [comment]
I have added a preview video too:
https://www.youtube.com/watch?v=pKZsnnaoIkg

**Comment by Timboy67678** [comment]
very nice @KN4CK3R
