### ISSUE TITLE
Address Notes

### ISSUE THREAD

**Issue by KittoniuM** [KN4CK3R/ReClass.NET#25]
there should be a button somewhere where you can add addresses and give them names 

like say you found local player at 0x17ae2660, you can change the name of it to "My Player" so all the refrences to 0x17ae2660 will be "My Player"

it will save you lots of time when you're trying to find pointers :D

**Comment by KN4CK3R** [comment]
I have added a new window in the "Process" menu.
![feature](https://user-images.githubusercontent.com/1666336/35103528-61e6e7d8-fc66-11e7-85a1-1fdd59b59ee6.jpg)
