### ISSUE TITLE
Add hex display for integer nodes

### ISSUE THREAD

**Issue by KittoniuM** [KN4CK3R/ReClass.NET#26]
There should be a DWORD or QWORD type (something ike that)

so you can see addreessses like 

> 0024 0000000140000024 Dword Color = 0xFFFFFF

or maybe add a checkbox somewhere that reads unsigned int's as hex instead of numbers ;D

or add a Hex display alongside the numbers

> 0024 0000000140000024 UInt32 Color = 16777215 (0xFFFFFF)

**Comment by KN4CK3R** [comment]
Why should the format for an unsigned type be hex?

**Comment by KittoniuM** [comment]
to save you time :D?
