### ISSUE TITLE
"highlight changed values" doesn't ever work for me

### ISSUE THREAD

**Issue by KittoniuM** [KN4CK3R/ReClass.NET#29]
Hi, i'm using the latest release (cant compile it my self) and noticed that theres a feature named Highlight Changed Values, it doesn't ever work, the hex values change but don't get highlighted

what am i doing wrong?

https://i.imgur.com/DdGqpvs.png

also, i tried using the default color scheme and my own, still nothing :(

https://i.imgur.com/tQI6mOl.png

**Comment by KN4CK3R** [comment]
Yes, doesn't work with v1.1 but works in the current source version.
