### ISSUE TITLE
"Get More Plugins" link label on PluginForm doesnt do anything

### ISSUE THREAD

**Issue by MarkHC** [KN4CK3R/ReClass.NET#3]
The "Get More Plugins" link label ([getMoreLinkLabel](https://github.com/KN4CK3R/ReClass.NET/blob/fcd292b421e1f2e1fa15ec7ea2c83dbf6d3d9047/Forms/PluginForm.Designer.cs#L382-L384)) doesn't do anything. 

Not sure what was your original idea with it (open a URL or just the /Plugins folder) but currently it just does nothing when you click on it.

Thanks.

**Comment by KN4CK3R** [comment]
Right, should open "https://github.com/KN4CK3R/ReClass.NET#plugins". But at the time I build the form the page doesn't exists.
