### ISSUE TITLE
Advanced Pointer Finder

### ISSUE THREAD

**Issue by KittoniuM** [KN4CK3R/ReClass.NET#38]
ok so i had this idea, basically

if you have a simple class in reclass with this setup:

0x0
0x8
0x10
0x18
0x20
0x28
0x30

but the game's offsets are shifted a bit so theres a pointer starting at 0x19

my idea is that mr. reclass will scan the data and look through all possible *and valid* pointers that it can get from the class

and if the pointer contains debug info (like vtable with debug info) it will be like "yo theres a class right here with a vtable!!)

what do you guys think of this?

**Comment by KN4CK3R** [comment]
You will not find a class in a real world program which has unaligned members.
