### ISSUE TITLE
Add a Boolean type

### ISSUE THREAD

**Issue by MarkHC** [KN4CK3R/ReClass.NET#5]
Not an issue, rather a suggestion.

It would be nice to have a bool type. Yeah I know we could just use uint8_t but still, that's not the same.

Thanks

**Comment by KN4CK3R** [comment]
I thougth about that too but the boolean type is a little bit special with his size. I could handle it like the bit type which can use different sizes. For the bool I would need to add a size display so you can see if you have a byte, short or int boolean. The easy way would be to make the boolean always 8 bit wide but that could fragment your class with lots of padding bytes.
What would you do?

**Comment by MarkHC** [comment]
I would just make it always 1 byte in size. Fragmentation would be the same as if you were to use a uint8_t/int8_t type so I don't think it would be a big problem.

**Comment by KN4CK3R** [comment]
I have added the bool type as a byte type now.
![](https://abload.de/img/unbenanntkqpg3.jpg)

--

To your designer question. I don't know what causes this error but you can fix it if you switch to x86. Then the designer works again (after reopening the form).
