### ISSUE TITLE
Process list not showing every process

### ISSUE THREAD

**Issue by jewsh** [KN4CK3R/ReClass.NET#9]
Lots of processes are omitted when trying to attach to something. Any specific reason for this?

**Comment by KN4CK3R** [comment]
Maybe you use ReClass.NET x64 to look for an x86 process or vice versa?

**Comment by jewsh** [comment]
I checked with both versions but neither worked. The process is x64 and CE has no problem listing/attaching to it.
However the old version of ReClass also did not list the process.

**Comment by KN4CK3R** [comment]
Which process are you talking about?

**Comment by jewsh** [comment]
x64 Aion client, shows up in any process list as "aion.bin"

**Comment by KN4CK3R** [comment]
Ok, I will download Aion and test it.

**Comment by KN4CK3R** [comment]
Just out of curiosity, you run ReClass as admin?

**Comment by jewsh** [comment]
Yeah but that wasn't the problem.
Apparently my AVs "real time protection" prevented ReClass from working correctly. Now that i turned it off it works as intended.
Sorry for the trouble.

**Comment by KN4CK3R** [comment]
Ok, good to know. 👍
